Vagrant.configure("2") do |config|
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
  config.vm.box = "centos65"
  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
  # the salt provisioner requires shared folders, which breaks easily, using shell instead
  # config.vm.synced_folder "../", "/srv/"
  # config.vm.provision :salt do |salt|
  #   salt.run_highstate = true
  #   salt.minion_config = "minion.conf"
  #   salt.install_type = "git"
  #   salt.install_args = "develop"
  # end
  config.vm.provision "shell", path: "../quick-start.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
